# -*- coding: utf-8 -*-
"""Houseprice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D3_YciXi-QhtjP_hrfU52nS8PF-2QlYW
"""

import pandas as pd

# Load the dataset
df = pd.read_csv("house price.csv")

# Basic structure of the dataset
print(df.info())

# Preview the first 5 rows
print(df.head())

# Dataset shape
print("Shape:", df.shape)

# Column names
print("Columns:", df.columns.tolist())

# Check for missing values
print("Missing Values:\n", df.isnull().sum())

# Check for duplicates
print("Duplicate Rows:", df.duplicated().sum())

import matplotlib.pyplot as plt
import seaborn as sns

# Set style
sns.set(style="whitegrid")

# Price distribution
plt.figure(figsize=(8, 4))
sns.histplot(df['price'], kde=True)
plt.title("Distribution of House Prices")
plt.show()

# Count of houses by number of bedrooms
plt.figure(figsize=(6, 4))
sns.countplot(x='bedrooms', data=df)
plt.title("Number of Bedrooms")
plt.show()

# Price vs Area
plt.figure(figsize=(8, 5))
sns.scatterplot(x='area', y='price', hue='furnishingstatus', data=df)
plt.title("Price vs Area")
plt.show()

# Target variable
target = 'price'

# Features (excluding the target)
features = [col for col in df.columns if col != target]

print("Target Variable:", target)
print("Features:", features)

